#
# Make figures for Flybys 2 paper

.PHONY: help
help:
	@echo "What do you want to make?"

.PHONY: figures
figures:
	./flyby_make_figures_for_paper.py

.PHONY: radiative-transfer
radiative-transfer:
	./flyby_run_mcfost.py
